### Site metadata

title: mbalc.github.io
description: A personal site of mbalc, a software engineer and a game developer.

### Build settings

url: https://mbalc.github.io
baseurl: /

theme: jekyll-theme-tao

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - docs/
  - LICENSE
  - Makefile
  - sample.png
  - README.md

### Theme settings

aux_links:
  "View source": "https://github.com/mbalc/mbalc.github.io"
